README.md
Full readme will be in a separate PR to https://github.com/docker-library/docs
=> MMF-1827 readme

4/Dockerfile
=> [#20] fix typescipt version to 3.6.3

4/Dockerfile
This solves issue 39, supporting shell sensor.
=> [#39] support ShellCheck sensor

DEVELOPER.md, README.md
This PR fixes simple typos found in README.md and DEVELOPER.md files.
I admit there are no significant problems that are solved by this PR. I only made this PR to fix very minor annoyances that I encounter when reading the documents in the codebase.
> Please be aware that we are not actively looking for feature contributions. We typically accept minor improvements and bug-fixes.
>
> Please ensure your pull request adheres to the following guidelines:
>
> - [x] Explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
> - [x] If the PR modifies or adds images, try to make sure the images run correctly on Linux
=> Fix typos in README.md and DEVELOPER.md

.github/workflows/hadolint-analysis.yml, 4/Dockerfile
ignore version pinning on apk 
ignore wget/curl mix as it will not be in the resulting image 
added pipefail option 
added workdir definition
=> linter-findings

.github/workflows/release.yml
Please be aware that we are not actively looking for feature contributions. We typically accept minor improvements and bug-fixes. 
Please ensure your pull request adheres to the following guidelines:
=> Release pipe fix

.github/workflows/release.yml
Please be aware that we are not actively looking for feature contributions. We typically accept minor improvements and bug-fixes. 
Please ensure your pull request adheres to the following guidelines:
=> Fixed typo in docker push command

.github/workflows/nightly.yml, .github/workflows/qa.yml
Attempt to automatically lookup the CLI version to install using the latest release name
=> Lookup SonarScanner CLI version from latest release

.github/workflows/rebuild.yml, .github/workflows/release.yml
Please be aware that we are not actively looking for feature contributions. We typically accept minor improvements and bug-fixes. 
Please ensure your pull request adheres to the following guidelines:
=> SQSCANNER-86 Push images to repox and docker hub.

.github/workflows/rebuild.yml
Please be aware that we are not actively looking for feature contributions. We typically accept minor improvements and bug-fixes. 
Please ensure your pull request adheres to the following guidelines:
=> Fix docker credentials

4/Dockerfile
was just a leftover from the rewrite of the Dockerfile with #98
fixes #103
=> removed no longer needed node path

CONTRIBUTING.md
=> NO-JIRA added contributing.md

.github/workflows/hadolint-analysis.yml, .github/workflows/rebuild.yml, 4/Dockerfile
DOCKER-7 and DOCKER-8 Switched parent image to alpine directly
DOCKER-5 pull signing key from keyserver. fixes #88
=> DOCKER-7 and DOCKER-8 Switched parent image to alpine directly

.github/workflows/rebuild.yml, 4/Dockerfile
=> DOCKER-3 11 and 15

4/Dockerfile
=> DOCKER-10 added default locales

4/Dockerfile, README.md
=> DOCKER-130 upgrade to alpine 3.17

4/Dockerfile
Duplicated PR of #172 in order to run internal tests not passing from external contribution
=> SONAR-19137 Bugfix/jc/no jira update node version from jammy

5/bin/entrypoint.sh
=> SQDEVOPS-253 - Replaces deprecated login with token

.github/workflows/release.yml
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
=> SCANDOCKER-3 Update release pipeline to support new versioning

Dockerfile
=> SCANDOCKER-9 Replace Busybox tar by GNU tar

.cirrus.yml
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
=> NO-JIRA Fix docker login

.cirrus.yml
This reverts commit 1bb96ade36663d531bfc3814e118225649e2a614.
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
=> Revert "BUILD-5775 Fix docker login"

Dockerfile
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
=> SCANDOCKER-40 Add LANG setup

README.md
Starting version 11, the docker image supports C&C++ through AutoConfig
=> Update Doc to reflect that C&C++ are supported

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[SCANDOCKER-47](https://sonarsource.atlassian.net/browse/SCANDOCKER-47)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last …
=> SCANDOCKER-47 Add Jira integration

README.md
[SCANDOCKER-48](https://sonarsource.atlassian.net/browse/SCANDOCKER-48)
[SCANDOCKER-48]: https://sonarsource.atlassian.net/browse/SCANDOCKER-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANDOCKER-48 Update license header for 2025

Dockerfile
[SCANDOCKER-49](https://sonarsource.atlassian.net/browse/SCANDOCKER-49)
[SCANDOCKER-49]: https://sonarsource.atlassian.net/browse/SCANDOCKER-49?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANDOCKER-49 Update the bundled Scanner CLI to 7.0.1.4817

.github/workflows/release.yml
[SCANDOCKER-52](https://sonarsource.atlassian.net/browse/SCANDOCKER-52)
[SCANDOCKER-52]: https://sonarsource.atlassian.net/browse/SCANDOCKER-52?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANDOCKER-52 Update GitHub actions

.github/workflows/release.yml
[SCANDOCKER-52](https://sonarsource.atlassian.net/browse/SCANDOCKER-52)
=> SCANDOCKER-52 Update SonarSource/gh-action_sbom to v3

Dockerfile
[SCANDOCKER-53](https://sonarsource.atlassian.net/browse/SCANDOCKER-53)
[SCANDOCKER-53]: https://sonarsource.atlassian.net/browse/SCANDOCKER-53?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANDOCKER-53 Update to SonarScanner CLI 7.0.2

Dockerfile
[SCANDOCKER-55](https://sonarsource.atlassian.net/browse/SCANDOCKER-55)
[SCANDOCKER-55]: https://sonarsource.atlassian.net/browse/SCANDOCKER-55?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANDOCKER-55 Update Scanner CLI to support the US region

README.md
[SCANDOCKER-54](https://sonarsource.atlassian.net/browse/SCANDOCKER-54)
* Forcing image rebuilt to upgrade Python to 3.9.21 and get rid of the current unique high vulnerability in Python 3.9.20
----
We will try to …
=> SCANDOCKER-54 Solve some Mend vulnerabilities

Dockerfile
[SCANDOCKER-60](https://sonarsource.atlassian.net/browse/SCANDOCKER-60)
[SCANDOCKER-60]: https://sonarsource.atlassian.net/browse/SCANDOCKER-60?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANDOCKER-60 Update embedded node.js to version 22

Dockerfile
[SCANDOCKER-62](https://sonarsource.atlassian.net/browse/SCANDOCKER-62)
[SCANDOCKER-62]: https://sonarsource.atlassian.net/browse/SCANDOCKER-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANDOCKER-62 Update Scanner CLI to 7.2
